Fix for RPC memory leak
imodeljs/imodeljs pull request #1044
Opened 2021-03-25 17:51 UTC by swbsi

2021-03-25 17:53 UTC, pmconne approved these changes

2021-03-29 12:27 UTC, calebmshafer requested changes
@swbsi looks like the roc-interface-full-stack-tests are failing. Here's the link to the failure,

https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=819819&view=logs&j=230f0658-f954-5875-4713-0dcc89b6e66c&t=f0fea0fa-cfa7-5408-7a11-d3c4abbacfb3

2021-03-29 13:55 UTC, calebmshafer approved these changes

2021-03-29 20:39 UTC, calebmshafer commented
@Mergifyio backport release/2.14.x

2021-03-30 01:15 UTC, merged