View creator api public release
imodeljs/imodeljs pull request #1076
Opened 2021-03-30 18:20 UTC by roopksaini

2021-03-30 18:24 UTC, pmconne commented on core/frontend/src/ViewCreator2d.ts
>    useSeedView?: boolean;
Elaborate on what this does. How is "seed" view selected?

2021-03-30 18:25 UTC, pmconne commented on core/frontend/src/ViewCreator2d.ts
> +/** @public Options for creating a 2d [[ViewState]] via [[ViewCreator2d]] */
Put release tags on separate (last) line of doc comments.

2021-03-30 18:26 UTC, pmconne commented on core/frontend/src/ViewCreator2d.ts
> + * @public API for creating a [[ViewState]] for a 2D model ([[GeometricModel2dState]]).
`[[ViewState]]` => `[[ViewState2d]]`.

2021-03-30 18:27 UTC, pmconne commented on core/frontend/src/ViewCreator2d.ts
> + * @public API for creating a [[ViewState]] for a 2D model ([[GeometricModel2dState]]).
`[[iModelConnection]] is not a valid link.

2021-03-30 18:30 UTC, pmconne requested changes
Documentation comments will appear on our public APi reference. Please document clearly and thoroughly using complete sentences, avoiding abbreivations, etc. Link to related APIs - e.g., add to `ViewCreator2d` something like `@see [[ViewCreator3d]] to create a view for a 3d model.`.

2021-04-07 20:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=1076) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=1076) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/imodeljs/imodeljs?pullRequest=1076) it.</sub>

2021-04-12 13:20 UTC, pmconne commented
@roopksaini do you plan to finish up this PR?

2021-04-16 16:07 UTC, roopksaini commented
@pmconne Updated. Kindly review.

2021-04-16 16:16 UTC, pmconne approved these changes

2021-04-17 14:40 UTC, merged