Ensure electron frontends cannot access files outside of installer path
imodeljs/imodeljs pull request #1135
Opened 2021-04-07 14:46 UTC by adamhock

Electron users cannot access files outside of installer path

2021-04-07 14:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=1135) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=1135) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/imodeljs/imodeljs?pullRequest=1135) it.</sub>

2021-04-07 14:53 UTC, DanEastBentley requested changes
Run "rush clean" before "rush build" and "rush extract-api" to prevent these false changes in the *.md files.

2021-04-08 14:29 UTC, wgoehrig commented on core/electron-manager/src/backend/ElectronHost.ts
> +    let regexp = ["..", "#", "?", "*", "$"];
I think there's probably a simpler way to do this...

Note that below, we use `fs.realpathSync` below to get a fully resolved _absolute_ path.  So we don't need to ban relative paths or other characters, we just need to check that the resolved path is still inside webResourcesPath, right?

2021-04-08 19:56 UTC, wgoehrig commented on core/electron-manager/src/backend/ElectronHost.ts
> +      throw new Error("Access outside that path is prohibited");
"that path" is ambiguous - how does:

```suggestion
      throw new Error(`Access to files outside installation directory (${this.webResourcesPath}) is prohibited`);
```

sound?

2021-04-09 13:05 UTC, DanEastBentley approved these changes

2021-04-09 13:10 UTC, kabentley commented on core/electron-manager/src/backend/ElectronHost.ts
>      // NEEDS_WORK: Remove this after migration to DesktopAuthorizationClient
@ramanujam-raman do you know what this is? Can it be removed?

2021-04-12 18:44 UTC, wgoehrig approved these changes

2021-04-15 15:01 UTC, merged