Fixed timeout (hanging issue) error
imodeljs/imodeljs pull request #1171
Opened 2021-04-09 19:08 UTC by saemjeon

Fix hanging issue when env doesn't have a valid imjs_oidc_browser_test_redirect_uri.

2021-04-13 16:00 UTC, wgoehrig requested changes

2021-04-13 16:00 UTC, wgoehrig commented on tools/oidc-signin-tool/src/TestBrowserAuthorizationClient.ts
> +    if (undefined !== errMsgText && null !== errMsgText)
Maybe in that case the error message should just be `"Unknown error page detected"` or something.

2021-04-13 18:32 UTC, saemjeon commented on tools/oidc-signin-tool/src/TestBrowserAuthorizationClient.ts
> +      console.log(title);
Removed the debug message.

2021-04-13 18:34 UTC, saemjeon commented on tools/oidc-signin-tool/src/TestBrowserAuthorizationClient.ts
> +    if (undefined !== errMsgText && null !== errMsgText)
I agree with you. I added a `null` check.

2021-04-14 18:11 UTC, wgoehrig approved these changes

2021-04-15 14:16 UTC, merged