Fix acs rotation and remove unneeded clones.
imodeljs/imodeljs pull request #1172
Opened 2021-04-10 11:35 UTC by bbastings

Bug with Matrix3d.inverse when (this === result) that needs to be looked at.
Should be scaleColumns, not scaleRows.
getOrigin and getRotation return clones, can use createRefs to avoid another copy.

2021-04-10 12:01 UTC, RBBentley approved these changes

2021-04-10 13:43 UTC, pmconne approved these changes

2021-04-12 12:48 UTC, EarlinLutz approved these changes

2021-04-12 12:56 UTC, mgooding approved these changes

2021-04-12 12:57 UTC, mgooding commented on core/geometry/src/test/geometry3d/RotMatrix.test.ts
> +describe.only("Matrix3d", () => {
remove only?

2021-04-12 12:58 UTC, mgooding requested changes
inadvertent only left in?

2021-04-12 13:22 UTC, EarlinLutz commented on core/geometry/src/test/geometry3d/RotMatrix.test.ts
> +describe.only("Matrix3d", () => {
(Fixed. TX)

2021-04-12 13:34 UTC, mgooding approved these changes

2021-04-12 19:03 UTC, merged