Webpack bug fixes
imodeljs/imodeljs pull request #1253
Opened 2021-04-21 21:58 UTC by saemjeon

Create tests for webpack plugins

2021-05-04 18:06 UTC, wgoehrig requested changes

2021-05-04 18:06 UTC, wgoehrig commented on tools/webpack-core/src/test/RequireMagicCommentsPlugin.test.ts
> +            test: /webpack: *external/i,
This also goes for tests C & D

2021-05-04 18:06 UTC, wgoehrig commented on tools/webpack-core/src/test/RequireMagicCommentsPlugin.test.ts
> +  it("C: sucess with external comments with with resolve not converted", async () => {
nit: typo (with with)

same for tests D-F

2021-05-04 18:06 UTC, wgoehrig commented on tools/webpack-core/src/test/CopyExternalsPlugin.test.ts
> +    expect(logging[1].message).to.be.include(`"eslint" included at lib\\test\\assets\\copy-externals-plugin-test\\copyEslintTest.js`);
This probably applies to all of these logging assertions...

2021-05-06 18:09 UTC, saemjeon commented on tools/webpack-core/src/test/OptionalDependenciesPlugin.test.ts
> +    /* eslint-enalbe @typescript-eslint/naming-convention */
Naming convention for node_modules I believe. It was asking for camelCase.

2021-05-17 18:08 UTC, SaemJeon commented on tools/webpack-core/src/test/CopyExternalsPlugin.test.ts
> +    expect(fs.existsSync(path.join(__dirname, "dist/node_modules/@bentley/imodeljs-native"))).to.be.true;
I believe it is `@bentley/imodeljs-native` is found from the regular node_modules directory.

2021-05-28 19:23 UTC, wgoehrig commented on tools/webpack-core/src/test/CopyExternalsPlugin.test.ts
> +    expect(fs.existsSync(path.join(__dirname, "dist/node_modules/@bentley/imodeljs-native"))).to.be.true;
OK, let's create a "fake" `@bentley/imodeljs-native` in `lib/test/assets/copy-externals-plugin-test/node_modules/` then...

I don't like the tests resolving anything in the root node_modules dir

2021-06-08 16:38 UTC, wgoehrig commented on tools/webpack-core/src/test/CopyExternalsPlugin.test.ts
> +    expect(fs.existsSync(path.join(__dirname, "dist/node_modules/@bentley/imodeljs-native"))).to.be.true;
@SaemJeon I thought we agreed to just remove this test?

2021-06-08 19:54 UTC, wgoehrig approved these changes

2021-06-16 02:50 UTC, merged