Save layer visibility.
imodeljs/imodeljs pull request #1557
Opened 2021-06-02 20:21 UTC by mdastous-bentley

@pmconne What do you think of this?  We want the layer visibility (sub-layer visibility is already fine)  to be saved.  As a side effect, if your visible flag was undefined, then it will now default to 'true' if you do the json roundtrip with MapLayerSettings.  The behaviour is similar to 'formatId' which defaults to 'WMS' if unspecified.

2021-06-02 20:29 UTC, pmconne commented
Seems like an oversight that it wasn't being included by `toJSON`, right?
I get a little grossed out by optional boolean properties that default to `true` (`transparentBackground` also does this).
Can you update the documentation of those two properties to specify they default to true? Currently, the following suggests the opposite:
```
  /** True to indicate background is tranparent */
  transparentBackground?: boolean;
```

2021-06-02 20:30 UTC, pmconne commented
Would you mind also figuring out why the MapLayerSettings constructor bypasses the `no-undef-init` eslint rule and ideally make it not have to?

2021-06-03 11:50 UTC, mdastous-bentley commented
> Seems like an oversight that it wasn't being included by `toJSON`, right?
> I get a little grossed out by optional boolean properties that default to `true` (`transparentBackground` also does this).
> Can you update the documentation of those two properties to specify they default to true? Currently, the following suggests the opposite:
> 
> ```
>   /** True to indicate background is tranparent */
>   transparentBackground?: boolean;
> ```

Actually its optional in MapLayerProps, but defaults to true when used to initialize MapLayerSettings (which is misleading).  Should we document the defaults in MapLayerProps doc anyway?

2021-06-03 11:59 UTC, pmconne commented
I don't understand what distinction you are making. The JSON property is optional; if it is omitted, MapLayerSettings.fromJSON() will default it to true. That should be documented in MapLayerProps (as should all default values).

2021-06-03 12:32 UTC, mdastous-bentley commented
I also see maxZoom on MapLayerProps, but missing MapLayerSettings. It  doesnt seem to have any use.

2021-06-03 12:38 UTC, pmconne commented
> I also see maxZoom on MapLayerProps, but missing MapLayerSettings. It doesnt seem to have any use.

MapLayerSource.fromJSON() takes its json as `any` (why?!) and pulls a `maxZoom` out of it, among other MapLayerProps properties...

2021-06-03 19:31 UTC, pmconne requested changes

2021-06-03 19:31 UTC, pmconne commented on core/common/src/MapLayerSettings.ts
> +  /** True to indicate background is transparent.  If omitted, defaults to 'true' in MapLayerSettings.fromJSON() */
It also defaults to true in MapLayerSource.fromJSON(), no? I would just say it defaults to true.

2021-06-03 19:31 UTC, pmconne commented on core/frontend/src/tile/map/MapLayerSources.ts
> +interface MapLayerSourceProps extends MapLayerProps
Weird that this inherits properties like `visible` that it are not used by MapLayerSource? Is there really an inheritance relationship between them or just a coincidental similarity?

2021-06-03 19:31 UTC, pmconne commented on core/frontend/src/tile/map/MapLayerSources.ts
> +      baseMap, json.transparentBackground === undefined ? true : json.transparentBackground,
`false !== json.transparentBackground` would make it much easier to tell what's going on.

2021-06-03 19:31 UTC, pmconne commented on core/frontend/src/tile/map/MapLayerSources.ts
> +  private constructor(public formatId: string, public name: string, public url: string, public baseMap = false, public transparentBackground?: boolean, public userName?: string, public password?: str
nitpick but I hate these constructors that declare half a dozen class members inline - they are convenient once, for the author who gets to type a little less, and inconvenient forever, for everyone else who has to parse them.

2021-06-03 19:33 UTC, pmconne commented on core/frontend/src/tile/map/MapLayerSources.ts
> +  private constructor(public formatId: string, public name: string, public url: string, public baseMap = false, public transparentBackground?: boolean, public userName?: string, public password?: str
Given the constructor is private and only called by `fromJson`, consider making it accept MapLayerSourceProps directly so you're not handling default values in two places.

2021-06-04 19:37 UTC, mdastous-bentley commented
@pmconne Code updated based on your comments.  Are we good to go ?

2021-06-04 19:51 UTC, pmconne approved these changes

2021-06-04 19:52 UTC, pmconne commented
> @pmconne Code updated based on your comments. Are we good to go ?

LGTM, gotta hassle the other required reviewers.

2021-06-05 02:28 UTC, bsteinbk approved these changes

2021-06-07 11:59 UTC, merged