Support scientific visualization in graphics created on the frontend
imodeljs/imodeljs pull request #1627
Opened 2021-06-15 11:14 UTC by pmconne

Sunand's application team wants to produce graphics on the frontend from polyfaces with aux data and have the meshes be deformed and/or recolored using AnalysisStyle.
Cleaned up and promoted AnalysisStyle APIs.
Ported native code for building AuxChannelTable from PolyfaceAuxData.
TODO: Add a keyin to display-test-app to serve as the basis for a showcase sample.
TODO: Remove analysis-importer.

Incidental changes:
ThematicDisplay.toJSON() omits properties that match the defaults, instead of producing `undefined` (which becomes `null` when serialized).
Clean up bang-happy ThematicDisplayEditor code.

2021-06-15 11:48 UTC, markschlosseratbentley approved these changes

2021-06-15 11:48 UTC, markschlosseratbentley approved these changes
This looks overall good to me - particularly the thematic changes.

2021-06-15 11:49 UTC, pmconne commented
> This looks overall good to me - particularly the thematic changes.

Thanks but it's not ready for review yet.

2021-06-15 11:56 UTC, markschlosseratbentley commented
> > This looks overall good to me - particularly the thematic changes.
> 
> Thanks but it's not ready for review yet.

@pmconne - Missed the 'draft' status.  Let me know when and I'll take another look.

2021-06-21 18:42 UTC, mgooding approved these changes

2021-06-21 18:58 UTC, markschlosseratbentley requested changes
Running into following test build error:
==[ core-full-stack-tests ]======================================[ 65 of 88 ]==
src/frontend/standalone/ViewportChangedEvents.test.ts(236,131): error TS2345: Argument of type '{ inputName: string; }' is not assignable to parameter of type 'AnalysisStyleProps'.
  Object literal may only specify known properties, and 'inputName' does not exist in type 'AnalysisStyleProps'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! core-full-stack-tests@ build:tests: `tsc 1>&2 && npm run webpack:frontend`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the core-full-stack-tests@ build:tests script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mark.Schlosser\AppData\Roaming\npm-cache\_logs\2021-06-21T18_56_12_547Z-debug.log
Returned error code: 2
"core-full-stack-tests" failed to build.

2021-06-21 18:59 UTC, markschlosseratbentley commented
Running into following test build error:
==[ core-full-stack-tests ]======================================[ 65 of 88 ]==
src/frontend/standalone/ViewportChangedEvents.test.ts(236,131): error TS2345: Argument of type '{ inputName: string; }' is not assignable to parameter of type 'AnalysisStyleProps'.
Object literal may only specify known properties, and 'inputName' does not exist in type 'AnalysisStyleProps'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! core-full-stack-tests@ build:tests: tsc 1>&2 && npm run webpack:frontend
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the core-full-stack-tests@ build:tests script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Mark.Schlosser\AppData\Roaming\npm-cache_logs\2021-06-21T18_56_12_547Z-debug.log
Returned error code: 2
"core-full-stack-tests" failed to build.

2021-06-21 19:01 UTC, markschlosseratbentley commented on core/common/src/AnalysisStyle.ts
> -/** Properties for display of analysis data
Running into following test build error:
==[ core-full-stack-tests ]======================================[ 65 of 88 ]==
src/frontend/standalone/ViewportChangedEvents.test.ts(236,131): error TS2345: Argument of type '{ inputName: string; }' is not assignable to parameter of type 'AnalysisStyleProps'.
Object literal may only specify known properties, and 'inputName' does not exist in type 'AnalysisStyleProps'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! core-full-stack-tests@ build:tests: tsc 1>&2 && npm run webpack:frontend
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the core-full-stack-tests@ build:tests script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Mark.Schlosser\AppData\Roaming\npm-cache_logs\2021-06-21T18_56_12_547Z-debug.log
Returned error code: 2
"core-full-stack-tests" failed to build.

2021-06-21 20:38 UTC, markschlosseratbentley approved these changes

2021-06-21 20:38 UTC, markschlosseratbentley commented on core/common/src/AnalysisStyle.ts
> -/** Properties for display of analysis data
@pmconne Feel free to resolve this conversation on your own to get this merged in once all in good shape.

2021-06-21 21:16 UTC, calebmshafer approved these changes
Approving rush.json, vscode and pnpm-lock updates.

2021-06-22 07:45 UTC, EarlinLutz approved these changes

2021-06-22 12:00 UTC, RBBentley approved these changes

2021-06-22 12:00 UTC, merged