Add changesetIndex in addition to changesetId to IModelDb.
imodeljs/imodeljs pull request #1727
Opened 2021-06-28 12:27 UTC by kabentley

Of course since old versions didn't save it, it may be `undefined`. 

Relies on [this PR](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/174373)

2021-06-28 12:30 UTC, pmconne requested changes
lint, extract-api, rush change.

2021-06-28 12:48 UTC, kabentley commented
> lint, extract-api, rush change.

All done. Working on NextVersion

2021-07-13 11:02 UTC, pmconne requested changes
Merge conflicts in imodeljs-backend.exports.csv.

2021-07-13 11:02 UTC, pmconne commented on common/api/summary/imodeljs-backend.exports.csv
> +<<<<<<< HEAD
Fix merge conflict.

2021-07-13 11:50 UTC, pmconne approved these changes

2021-07-13 12:17 UTC, bsteinbk approved these changes

2021-07-13 12:22 UTC, pmconne commented
Please merge ASAP - native PR already merged.

2021-07-13 12:51 UTC, merged