Update to Electron 10.x
imodeljs/imodeljs pull request #176
Opened 2020-11-04 22:36 UTC by calebmshafer

Update to Electron 10.1.3 in the repository and as the peerDep version for `@bentley/electron-manager`.

2020-11-04 22:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=176) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=176) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: calebmshafer<br/>:x: ramanujam-raman<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/imodeljs/imodeljs?pullRequest=176) it.</sub>

2020-11-04 23:57 UTC, ColinKerr approved these changes

2020-11-05 06:16 UTC, grigasp approved these changes

2020-11-05 11:05 UTC, pmconne approved these changes

2020-11-05 12:43 UTC, bsteinbk approved these changes

2020-11-05 14:17 UTC, swbsi approved these changes

2020-11-06 13:31 UTC, wgoehrig requested changes

2020-11-06 13:56 UTC, calebmshafer commented on clients/rbac/package.json
> +    "test:integration": "npm run webpackTests && npm run test:integration:chrome",
These are the ones that were failing due to the timing issue with certa/electron that Raman was running into.  We talked about just disabling the single test for now to get this merged and then circle back to it once we could come up with something better for Certa.

2020-11-11 18:13 UTC, wgoehrig commented
@calebmshafer This PR has whitespace-only changes caused by a (recently-fixed) bug in our commit hooks.

Please run the following locally to revert these changes:

```
git co master
git pull
git co <your branch>
git merge master
rush fix-copyrights
```

2020-11-11 22:42 UTC, ramanujam-raman approved these changes

2020-11-11 22:46 UTC, wgoehrig approved these changes

2020-11-17 15:08 UTC, pmconne approved these changes

2020-11-17 15:10 UTC, paulius-valiunas approved these changes

2020-11-17 16:06 UTC, calebmshafer commented
@scsewall or @swwilson-bsi mind taking a look?

2020-11-17 16:18 UTC, scsewall approved these changes

2020-11-18 02:42 UTC, merged