Reality tile reprojection
imodeljs/imodeljs pull request #1906
Opened 2021-07-21 12:43 UTC by RBBentley

2021-07-21 12:55 UTC, pmconne requested changes
rush change, extract-api

2021-07-21 12:56 UTC, pmconne commented
Have you queued an ImageTests run?

2021-07-21 12:57 UTC, pmconne commented
Think @AlainRobertAtBentley ought to review?

2021-07-21 12:58 UTC, paulius-valiunas approved these changes
Approving for whitespace changes in eslint plugin

2021-07-21 14:24 UTC, RBBentley reviewed
> Have you queued an ImageTests run?

Yes.... in progress.  I'll add more test cases for the OSM buildings as well.

2021-07-21 15:12 UTC, RBBentley commented
> rush change, extract-api

Done

2021-07-21 17:40 UTC, RBBentley commented
> Have you queued an ImageTests run?

Only difference was correction of the building heights in Philadelphia (fixed by this PR)
![image](https://user-images.githubusercontent.com/20863871/126534701-96c9afaf-212c-4d75-89bc-feb873997f5c.png)

2021-07-21 17:42 UTC, RBBentley commented
> Think someone like @AlainRobertAtBentley ought to review?

Added Alain as reviewer

2021-07-21 18:36 UTC, pmconne commented on core/frontend/src/tile/RealityTileTree.ts
> +      const dbToRoot = this.iModelTransform.inverse()!;
Handle non-invertible transform?

2021-07-21 18:50 UTC, RBBentley commented on core/frontend/src/tile/RealityTileTree.ts
> +      const dbToRoot = this.iModelTransform.inverse()!;
Done...

2021-07-21 20:19 UTC, RBBentley commented on core/frontend/src/tile/RealityTile.ts
> + * These step children are subdivided until they are small enough to be accurately reprojected - this is controlled by the additiveRefinementThreshold (currently 20KM).
Good point - I ended up with 20Km empirically -- trying to come up with a value that would not produce too many stepchildren.   I would prefer to use a smaller value but even 2000M causes excessive subdivision and thousands of tiles (I tried it).

2021-07-21 20:22 UTC, RBBentley commented on core/frontend/src/tile/RealityTile.ts
> + * These step children are subdivided until they are small enough to be accurately reprojected - this is controlled by the additiveRefinementThreshold (currently 20KM).
FWIW -- The tile radius is grossly exaggerated as it is calculated from the range diagonal in a bounding box aligned to the world.

2021-07-21 20:23 UTC, RBBentley commented on core/frontend/src/tile/RealityTile.ts
> + * In this case we create addtitional "step" children (grandchildren etc. ) that will clipped portions display the their ancestor's additive geometry.
Fixed, Thanks.

2021-07-21 20:56 UTC, AlainRobertAtBentley commented on core/frontend/src/tile/RealityTile.ts
> + * These step children are subdivided until they are small enough to be accurately reprojected - this is controlled by the additiveRefinementThreshold (currently 20KM).
Okay, We will try it out with 20km and see how it performs.

2021-07-21 20:59 UTC, AlainRobertAtBentley commented
I had Richard review (he knows more about tiles and ECEF and transform than I do) and it said it looked good to him. The GeoConverter stuff appears correct too.

2021-07-21 21:01 UTC, AlainRobertAtBentley approved these changes

2021-07-22 10:21 UTC, pmconne commented
I opened the TPB iModel. Turned buildings on and background map off. Panned slightly left from initial view then zoomed out a couple times. The app froze with 6 active tiles loading. I killed it after ~2 minutes.

2021-07-22 10:24 UTC, pmconne commented
After keying in `fdt set building display`, frustum does not appear to get expanded until a view navigation occurs. Until then, buildings are clipped by previous near/far planes.

2021-07-22 10:29 UTC, pmconne requested changes
Please investigate OOM crashes.

I opened the TPB iModel. Turned buildings on and background map off. Panned slightly left from initial view then zoomed out a couple times. The app froze with 6 active tiles loading. I killed it after ~2 minutes.
Reproduced this in similar manner again. Application window went blank white after ~30 seconds (render process gone).
Reproduced a third time (disabling map is not required). Memory usage reported by Task Manager rapidly skyrockets past 4 GB before the render process dies.

2021-07-22 10:34 UTC, RBBentley commented
> Please investigate OOM crashes.
> 
> I opened the TPB iModel. Turned buildings on and background map off. Panned slightly left from initial view then zoomed out a couple times. The app froze with 6 active tiles loading. I killed it after ~2 minutes.
> Reproduced this in similar manner again. Application window went blank white after ~30 seconds (render process gone).
> Reproduced a third time (disabling map is not required). Memory usage reported by Task Manager rapidly skyrockets past 4 GB before the render process dies.

Yes - Looking at this now.  For some reason there is a tile where the subdivision never finishes.

2021-07-22 11:02 UTC, RBBentley commented
> Please investigate OOM crashes.
> 
> I opened the TPB iModel. Turned buildings on and background map off. Panned slightly left from initial view then zoomed out a couple times. The app froze with 6 active tiles loading. I killed it after ~2 minutes.
> Reproduced this in similar manner again. Application window went blank white after ~30 seconds (render process gone).
> Reproduced a third time (disabling map is not required). Memory usage reported by Task Manager rapidly skyrockets past 4 GB before the render process dies.

Fixed.   I was stupidly testing radius for the subdivision termination which is never reduced when you quadrant the parent.

2021-07-22 11:06 UTC, RBBentley commented
@AlainRobertAtBentley  - After fixing the subdivision criteria where I was stupidly testing the tile radius, I was able to reduce the termination threshold to 2000M.   This reduces the potential altitude error to less than a meter.

2021-07-22 11:16 UTC, pmconne commented
Is 335 tiles an appropriate number to be selected when viewing this region?
![image](https://user-images.githubusercontent.com/22944042/126630812-cc11149e-fcb5-4dc0-b07e-47e84497a194.png)

Zoomed out with scene frozen:
![image](https://user-images.githubusercontent.com/22944042/126630931-4bb98d9d-2fe0-47cb-aa52-ba232d20428b.png)

2021-07-22 11:24 UTC, RBBentley commented
> Is 335 tiles an appropriate number to be selected when viewing this region?
> ![image](https://user-images.githubusercontent.com/22944042/126630812-cc11149e-fcb5-4dc0-b07e-47e84497a194.png)
> 
> Zoomed out with scene frozen:
> ![image](https://user-images.githubusercontent.com/22944042/126630931-4bb98d9d-2fe0-47cb-aa52-ba232d20428b.png)

Yes - Unfortunately this is.  In this region we have additive tiles contributing to the view from depth 3 all the way down to 14.  I have to include stepchildren for each.  It doesn't look quite as overly dense if you look at the reality range boxes "fdt reality bounds" which displays the boxes from the range corners- which are oriented more reasonably.

![image](https://user-images.githubusercontent.com/20863871/126631629-36dea8f7-c44b-436c-a069-9158f81f691d.png)

2021-07-22 11:25 UTC, pmconne commented
This top view of Exton is drawing over 3000 building tiles. FPS < 10 when stationary. It drops below 5 when moving the mouse cursor.
![image](https://user-images.githubusercontent.com/22944042/126631946-80047ff5-305b-4c66-80a8-1d8268b9665a.png)

2021-07-22 11:29 UTC, RBBentley commented
> This top view of Exton is drawing over 3000 building tiles. FPS < 10 when stationary. It drops below 5 when moving the mouse cursor.
> ![image](https://user-images.githubusercontent.com/22944042/126631946-80047ff5-305b-4c66-80a8-1d8268b9665a.png)

Yes - I see this.  I'm going to have to come up with a better criteria for ending the subdivision.

2021-07-22 20:32 UTC, RBBentley commented
> > This top view of Exton is drawing over 3000 building tiles. FPS < 10 when stationary. It drops below 5 when moving the mouse cursor.
> > ![image](https://user-images.githubusercontent.com/22944042/126631946-80047ff5-305b-4c66-80a8-1d8268b9665a.png)
> 
> Yes - I see this. I'm going to have to come up with a better criteria for ending the subdivision.

Fix pushed - Please retest...

2021-07-22 20:38 UTC, pmconne commented
> Fix pushed - Please retest...

Significantly improved.

2021-07-22 20:42 UTC, pmconne approved these changes

2021-07-23 10:46 UTC, pmconne commented
@Mergifyio update

2021-07-23 12:12 UTC, merged

2021-07-23 12:14 UTC, pmconne commented
@Mergifyio backport release/2.19.x