add no-internal rule
imodeljs/imodeljs pull request #191
Opened 2020-11-09 12:02 UTC by paulius-valiunas

2020-11-09 12:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=191) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=191) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/imodeljs/imodeljs?pullRequest=191) it.</sub>

2020-11-09 15:30 UTC, calebmshafer commented
@paulius-valiunas can you add some docs on how to use it, i.e. what it would look like in the eslint config?

2020-11-09 15:44 UTC, paulius-valiunas commented
@calebmshafer what would be a good place to document this?

2020-11-09 15:46 UTC, calebmshafer commented
> @calebmshafer what would be a good place to document this?

Can you add it to the readme for this package for now?  That seems the best/easiest place to put it to start with.

2020-11-11 18:12 UTC, wgoehrig requested changes
@paulius-valiunas This PR has whitespace-only changes caused by a (recently-fixed) bug in our commit hooks.

Please run the following locally to revert these changes:

```
git co master
git pull
git co <your branch>
git merge master
rush fix-copyrights
```

2020-11-12 13:47 UTC, calebmshafer requested changes
Tested it out and it works well.  It's a bit slow compared to some of the other rules so it'd be hard for some of the apps to have this as a pre-commit hook.  However, I know it's doing a fair amount of traversal up the hierarchy in some cases.

Any ideas on how to it could be made a bit faster?

2020-11-17 13:35 UTC, calebmshafer commented
@paulius-valiunas I hooked this up to the map-layers Extension to test it out with this config,

```
"@bentley/no-internal": [
  "error",
  {
    "tag": [
      "internal",
      "alpha"
    ]
  }
]
```

It didn't come back with any errors despite a few things in the Extension using alpha APIs;

- `ui/widget/AttachLayerPopupButton.tsx`: `MapLayerSourceStatus` is alpha
- `ui/widget/AttachLayerPopupButton.tsx`: `ListBox` is alpha
- `ui/widget/AttachLayerPopupButton.tsx`: `ListBoxItem` is alpha
- `ui/widget/AttachLayerPopupButton.tsx`: `OutsideClickEvent` is alpha
- `ui/widget/AttachLayerPopupButton.tsx`: `useOnOutsideClick` is alpha
- ``: `MapLayerProps` is alpha
- etc.

I think tried it out with adding "beta" to the list as well and it found a handful that time,

```
mapLayers.ts(39,7): error @bentley/no-internal : "UiItemsManager" is beta.
mapLayers.ts(39,7): error @bentley/no-internal : "UiItemsManager" is beta.
mapLayers.ts(55,5): error @bentley/no-internal : "Extension" is beta.
mapLayers.ts(55,5): error @bentley/no-internal : "Extension" is beta.
mapLayers.ts(62,5): error @bentley/no-internal : "UiItemsManager" is beta.
mapLayers.ts(62,5): error @bentley/no-internal : "UiItemsManager" is beta.
mapLayers.ts(73,3): error @bentley/no-internal : "ExtensionAdmin" is beta.
mapLayers.ts(73,3): error @bentley/no-internal : "ExtensionAdmin" is beta.
/ui/widget/SubLayersDataProvider.ts(38,14): error @bentley/no-internal : "PropertyRecord" is beta.
/ui/widget/SubLayersDataProvider.ts(38,14): error @bentley/no-internal : "PropertyRecord" is beta.
```

Any idea which types are being missed? Or maybe it's just missing `*.tsx` files?

2020-11-17 13:42 UTC, paulius-valiunas commented
> 
> 
> @paulius-valiunas I hooked this up to the map-layers Extension to test it out with this config,
> 
> ```
> "@bentley/no-internal": [
>   "error",
>   {
>     "tag": [
>       "internal",
>       "alpha"
>     ]
>   }
> ]
> ```
> 
> It didn't come back with any errors despite a few things in the Extension using alpha APIs;
> 
>     * `ui/widget/AttachLayerPopupButton.tsx`: `MapLayerSourceStatus` is alpha
> 
>     * `ui/widget/AttachLayerPopupButton.tsx`: `ListBox` is alpha
> 
>     * `ui/widget/AttachLayerPopupButton.tsx`: `ListBoxItem` is alpha
> 
>     * `ui/widget/AttachLayerPopupButton.tsx`: `OutsideClickEvent` is alpha
> 
>     * `ui/widget/AttachLayerPopupButton.tsx`: `useOnOutsideClick` is alpha
> 
>     * ``: `MapLayerProps` is alpha
> 
>     * etc.
> 
> 
> I think tried it out with adding "beta" to the list as well and it found a handful that time,
> 
> ```
> mapLayers.ts(39,7): error @bentley/no-internal : "UiItemsManager" is beta.
> mapLayers.ts(39,7): error @bentley/no-internal : "UiItemsManager" is beta.
> mapLayers.ts(55,5): error @bentley/no-internal : "Extension" is beta.
> mapLayers.ts(55,5): error @bentley/no-internal : "Extension" is beta.
> mapLayers.ts(62,5): error @bentley/no-internal : "UiItemsManager" is beta.
> mapLayers.ts(62,5): error @bentley/no-internal : "UiItemsManager" is beta.
> mapLayers.ts(73,3): error @bentley/no-internal : "ExtensionAdmin" is beta.
> mapLayers.ts(73,3): error @bentley/no-internal : "ExtensionAdmin" is beta.
> /ui/widget/SubLayersDataProvider.ts(38,14): error @bentley/no-internal : "PropertyRecord" is beta.
> /ui/widget/SubLayersDataProvider.ts(38,14): error @bentley/no-internal : "PropertyRecord" is beta.
> ```
> 
> Any idea which types are being missed? Or maybe it's just missing `*.tsx` files?

I'll have to look into these cases.
I didn't test this rule properly with enums and type aliases. Some of the other ones seem to be using a different way of declaring React components I haven't thought about. It's very good that you noticed these, because fishing out all the corner cases is the hardest part of writing a rule :)

2020-11-25 13:06 UTC, paulius-valiunas commented
@calebmshafer I just tested the rule with map-layers and got 265 problems. Did you run `rush install` before lint? Packages have to be installed for type resolution to work. I did have to fix enum members (for `MapLayerSourceStatus`), but the React components were detected without any changes
```
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(35,89): error @bentley/no-internal : "useSourceMapContext" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(54,62): error @bentley/no-internal : "MapLayerSource" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(58,51): error @bentley/no-internal : "MapLayerSource" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(58,51): error @bentley/no-internal : "MapLayerSource" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(58,51): error @bentley/no-internal : "MapLayerSource" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(59,30): error @bentley/no-internal : "MapLayerSourceStatus" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(60,17): error @bentley/no-internal : "attachMapLayer" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(60,17): error @bentley/no-internal : "attachMapLayer" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(60,17): error @bentley/no-internal : "attachMapLayer" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(61,29): error @bentley/no-internal : "MapLayerSource" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(62,25): error @bentley/no-internal : "MapLayerSource" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(63,24): error @bentley/no-internal : "MapLayerSource" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(64,29): error @bentley/no-internal : "MapLayerSource" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(65,29): error @bentley/no-internal : "MapLayerSource" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(66,28): error @bentley/no-internal : "MapLayerSource" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(69,17): error @bentley/no-internal : "invalidateRenderPlan" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(69,17): error @bentley/no-internal : "invalidateRenderPlan" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(69,17): error @bentley/no-internal : "invalidateRenderPlan" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(74,139): error @bentley/no-internal : "MapLayerSource" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(93,87): error @bentley/no-internal : "MapLayerSource" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(93,116): error @bentley/no-internal : "MapLayerSource" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(143,9): error @bentley/no-internal : "Listbox" is alpha.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(146,15): error @bentley/no-internal : "ListboxItem" is alpha.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(183,20): error @bentley/no-internal : "useOnOutsideClick" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\AttachLayerPopupButton.tsx(185,32): error @bentley/no-internal : "useSourceMapContext" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(23,7): error @bentley/no-internal : "MapImagerySettings" is alpha.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(23,7): error @bentley/no-internal : "mapImagery" is alpha.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(23,86): error @bentley/no-internal : "MapImagerySettings" is alpha.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(23,86): error @bentley/no-internal : "mapImagery" is alpha.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(24,12): error @bentley/no-internal : "MapLayerSettings" is alpha.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(24,12): error @bentley/no-internal : "MapImagerySettings" is alpha.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(24,12): error @bentley/no-internal : "mapImagery" is alpha.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(37,37): error @bentley/no-internal : "useSourceMapContext" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(41,14): error @bentley/no-internal : "baseMapTransparency" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(47,7): error @bentley/no-internal : "changeBaseMapTransparency" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(47,7): error @bentley/no-internal : "changeBaseMapTransparency" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(47,7): error @bentley/no-internal : "changeBaseMapTransparency" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(48,7): error @bentley/no-internal : "invalidateRenderPlan" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(48,7): error @bentley/no-internal : "invalidateRenderPlan" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(48,7): error @bentley/no-internal : "invalidateRenderPlan" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(59,58): error @bentley/no-internal : "MapLayerSource" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(59,77): error @bentley/no-internal : "MapLayerSource" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(82,23): error @bentley/no-internal : "MapLayerProps" is alpha.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(103,7): error @bentley/no-internal : "invalidateRenderPlan" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(103,7): error @bentley/no-internal : "invalidateRenderPlan" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(103,7): error @bentley/no-internal : "invalidateRenderPlan" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(111,7): error @bentley/no-internal : "changeBaseMapProps" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(111,7): error @bentley/no-internal : "changeBaseMapProps" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(111,7): error @bentley/no-internal : "changeBaseMapProps" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widget\BasemapPanel.tsx(112,7): error @bentley/no-internal : "invalidateRenderPlan" is internal.
D:\code\iModelJs\imodeljs\extensions\map-layers\src\ui\widge [...]

2020-11-25 13:17 UTC, EarlinLutz reviewed
Sorry, I'm not an appropriate reviewer for this.

2020-12-01 01:21 UTC, calebmshafer commented
@paulius-valiunas I just tried this again and still getting the same results.  Here are the steps I using to test this,

1. Add the config, pasted below, to the map-layers package.json
1. `rush clean && rush purge && rush install`
1. `rush build --to map-layers`
1. `cd extensions/map-layers`
1. `npm run lint`


Here's the config I used,

```
"eslintConfig": {
    "plugins": [
      "@bentley"
    ],
    "extends": "plugin:@bentley/imodeljs-recommended",
    "rules": {
      "@bentley/no-internal": [
        "error",
        {
          "tag": [
            "internal",
            "alpha"
          ]
        }
      ]
    }
  }
```

Here's the output from it,

```
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(26,14): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(26,31): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(26,63): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(26,98): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(31,26): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(31,40): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(31,53): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(31,66): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(38,40): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(38,55): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(39,22): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(41,22): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(42,35): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(50,71): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(52,99): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(52,108): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(62,13): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(63,45): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(71,97): error @bentley/no-internal : "MapSubLayerProps" is alpha.
/extensions/map-layers/src/ui/widget/SubLayersDataProvider.ts(71,106): error @bentley/no-internal : "MapSubLayerProps" is alpha.
```

2020-12-01 09:51 UTC, paulius-valiunas commented
@calebmshafer I'm confused, this time I checked out this branch, ran exactly the commands you wrote, and still got 265 errors. It looks like some weird caching bug, have you tried restarting VSCode before running `npm run lint`? Or maybe your local branch is a couple commits behind?

2020-12-16 14:54 UTC, calebmshafer commented
@paulius-valiunas just tried this again on a Windows machine and in our devcontainer.  Both of those seem to be working as you described. Now it's just my Mac that's still getting 20 problems instead of 265.

I tried restarting and updating my VSCode, and still no luck. Is there a specific place I can go to clear any caches ESLint has?

2020-12-17 14:15 UTC, paulius-valiunas commented
> Is there a specific place I can go to clear any caches ESLint has?

@calebmshafer Maybe `npm cache clear`?

2020-12-18 18:08 UTC, calebmshafer commented
@paulius-valiunas finally figured this out and it is MacOS specific.  The current glob patterns used everywhere, e.g. `./src/**/*.ts`, are not being correctly parsed in MacOS so instead of honoring the `**` it's just doing the first level of files. 

If I wrap that glob pattern in quotes `\"./src/**/*.ts\"` it works as it does on Linux and Windows.  This is kind of annoying but is similar to how it's handled for cpx.

I'll approve this PR since the rule itself is working and then make a new one to fix all of the glob patterns.  Can you check the ESLint issues to see if something is already open?

2020-12-18 18:08 UTC, calebmshafer approved these changes

2020-12-18 18:10 UTC, wgoehrig approved these changes

2021-01-04 14:56 UTC, merged