Footer Popup extends PopupProps
imodeljs/imodeljs pull request #199
Opened 2020-11-09 22:16 UTC by JKirchartz

FooterPopupProps should extent PopupProps instead of CommonProps to allow access to all internal props.

2020-11-09 22:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=199) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=199) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/imodeljs/imodeljs?pullRequest=199) it.</sub>

2020-11-09 22:40 UTC, calebmshafer commented
/AzurePipelines run

2020-11-10 13:39 UTC, bsteinbk approved these changes

2020-11-10 13:41 UTC, pmconne approved these changes
Not sure why separate approval needed for changelogs.

2020-11-10 13:51 UTC, JKirchartz commented
> Not sure why separate approval needed for changelogs.

I made the initial edit on GitHub yesterday afternoon, but it doesn't appear that the pre-commit hooks were causing the `rush change -v` (verification step) to fail because I never ran `rush change`. I cloned the project and generated the change on a different commit and pushed that up just now.

2020-11-10 17:06 UTC, JKirchartz commented on ui/ninezone/src/ui-ninezone/footer/Popup.tsx
> +export interface FooterPopupProps extends PopupProps {
I would like to use set [closeOnEnter from Popup](https://github.com/imodeljs/imodeljs/blob/2f380c48cf8351fba41aad73c3ab682dd324e51d/ui/core/src/ui-core/popup/Popup.tsx#L66) on the [Popup element in this module](https://github.com/imodeljs/imodeljs/blob/master/ui/ninezone/src/ui-ninezone/footer/Popup.tsx#L70).

Can I use a regular Popup element in place of a FooterPopup in the footer? Maybe I'm using the wrong element.

2020-11-10 18:56 UTC, GerardasB commented on ui/ninezone/src/ui-ninezone/footer/Popup.tsx
> +export interface FooterPopupProps extends PopupProps {
You could, but you would loose some of the styling and configuration. 
I was a bit worried about allowing to overwrite preconfigured props, but that should not be a problem. Let's go ahead and merge this.

2020-11-10 18:57 UTC, GerardasB approved these changes

2020-11-16 17:48 UTC, calebmshafer approved these changes

2020-11-16 17:48 UTC, calebmshafer commented
/AzurePipelines run

2020-11-19 02:33 UTC, calebmshafer commented
/azp run

2020-11-19 13:28 UTC, calebmshafer commented
@JKirchartz can you take a look at the build failures?

2020-11-20 18:00 UTC, JKirchartz commented
@calebmshafer I can't work past the build failures, I only really need the `closeOnEnter` prop added.

2020-11-20 18:40 UTC, calebmshafer commented
/azp run

2020-11-20 19:04 UTC, calebmshafer commented
@JKirchartz the build is failing due to API extractor.  Can you please do a clean build and then run `npm run extract-api` in the ui-ninezone package?

2020-11-24 20:04 UTC, calebmshafer requested changes
Adding this is an actual review instead of just a comment.  Would you be able to run the extract-api command to update those files?  This is blocking the CI build from passing.

2020-12-09 11:08 UTC, GerardasB commented
Closing in favor of #385

2020-12-09 11:08 UTC, closed without merging