Remove logger config
imodeljs/imodeljs pull request #2010
Opened 2021-08-06 15:35 UTC by pbell97

Removing logger config project and the few references to it. Adding it to the imodeljs-internal repo in a separate PR.

2021-08-06 15:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=2010) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=2010) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/imodeljs/imodeljs?pullRequest=2010) it.</sub>

2021-08-09 20:21 UTC, calebmshafer commented
@Mergifyio update

2021-08-09 20:25 UTC, calebmshafer requested changes
A minor comment on the docs update, otherwise looks good.

2021-08-09 20:25 UTC, calebmshafer commented on docs/learning/common/Logging.md
> +A service typically initializes and configures logging in its startup logic. Configuration can be based on the configuration parameters of the service, which may be set by the deployment mechanism. T
Duplicate `.` at the end of the second sentence.

2021-08-09 20:29 UTC, pmconne approved these changes

2021-08-09 20:36 UTC, calebmshafer approved these changes

2021-08-09 20:49 UTC, DanEastBentley approved these changes

2021-08-10 23:45 UTC, calebmshafer commented
@Mergifyio update

2021-08-11 00:42 UTC, merged