Improvements to tutorials
imodeljs/imodeljs pull request #207
Opened 2020-11-10 19:39 UTC by williamkbentley

2020-11-10 20:22 UTC, Josh-Schifter requested changes

2020-11-10 20:22 UTC, Josh-Schifter commented on docs/learning/tutorials/create-test-imodel-sample.md
> +Soccer stadium in Singapore. Features landscape details and a metro station. Largest iModel.
I'd prefer "This is the largest sample iModel." rather than "Largest iModel".

2020-11-10 20:22 UTC, Josh-Schifter commented on docs/learning/tutorials/create-test-imodel-sample.md
> +Simple processing plant. Smallest iModel.
"This is the smallest sample iModel."

2020-11-10 20:22 UTC, Josh-Schifter commented on docs/learning/tutorials/develop-agent.md
> +- Have access to a cloud hosted iModel. If you do not have access to one, [follow a create online iModel tutorial]($docs/learning/tutorials/index.md)
I'd prefer:

If you do not have access to one, follow one of our tutorials to [create an online iModel](blah/blah/blah).

2020-11-10 20:22 UTC, Josh-Schifter commented on docs/learning/tutorials/use-existing-imodel.md
>  If you already have access to an iModel this will guide you through locating the name of the Project, iModel, and viewing the iModel in an iModel.js based online viewer.
"iTwin.js" instead of "iModel.js".  Probably worth looking around for more occurrences.

2020-11-10 21:18 UTC, Josh-Schifter approved these changes

2020-11-12 00:04 UTC, calebmshafer commented on docs/learning/tutorials/create-test-imodel-sample.md
> +- Select a dataset from the dropdown.
nit: mind either dropping the `.` or add it to the other bullets.  I forgot if we have a good standard in our docs or not...

2020-11-12 00:05 UTC, calebmshafer commented
@williamkbentley any idea why the stadium and retail building pngs are so much larger than the others?

2020-11-12 13:36 UTC, williamkbentley commented
> @williamkbentley any idea why the stadium and retail building pngs are so much larger than the others?

Not sure. They are a few pixels larger and more colorful. They still aren't _that_ big.

2020-11-12 13:40 UTC, calebmshafer commented
> > @williamkbentley any idea why the stadium and retail building pngs are so much larger than the others?
> 
> Not sure. They are a few pixels larger and more colorful. They still aren't _that_ big.

fair enough, I just noticed when moving the repo to GH most of the size of the repo comes from a handful of images in the docs folder.  Especially if they're moved around folders later, it's a new copy each time since git can't diff them.

2020-11-12 13:40 UTC, calebmshafer approved these changes

2020-11-12 14:22 UTC, merged