Fix graphicbuilder transform
imodeljs/imodeljs pull request #2164
Opened 2021-08-30 13:00 UTC by markschlosseratbentley

Geometry created by a GraphicBuilder needs to have its specified placement transform applied properly.  This PR also modularizes some test functionality used by tests in frontend/src/test/render/webgl/

2021-08-30 13:08 UTC, pmconne requested changes

2021-08-30 13:08 UTC, pmconne commented on core/frontend/src/render/primitives/geometry/GeometryPrimitives.ts
> +    if (undefined !== polyfaceList)
Avoid wasting time applying identity transform (typical case) here and in getStrokes.

2021-08-30 13:41 UTC, pmconne approved these changes

2021-08-30 14:08 UTC, markschlosseratbentley commented
@mergifyio update

2021-08-30 19:22 UTC, pmconne commented
@Mergifyio update

2021-08-30 19:59 UTC, merged

2021-09-07 14:00 UTC, markschlosseratbentley commented
@Mergifyio backport release/2.19.x