Presentation. Deprecated rule cleanup
imodeljs/imodeljs pull request #2312
Opened 2021-09-21 13:34 UTC by karolisab

Removed deprecated presentation rules.

Updated old json rule configurations to use the latest rule versions.

Updated documentation.

2021-09-21 13:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=2312) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=2312) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/imodeljs/imodeljs?pullRequest=2312) it.</sub>

2021-09-22 05:27 UTC, grigasp requested changes

2021-09-22 05:27 UTC, grigasp commented on presentation/common/src/presentation-common/rules/content/modifiers/RelatedPropertiesSpecification.ts
>   * Sub-specification to include additional related instance properties.
Missing doc link
```
 * @see [More details]($docs/learning/presentation/Content/RelatedPropertiesSpecification.md)
```

2021-09-22 05:27 UTC, grigasp commented on presentation/common/src/presentation-common/rules/content/modifiers/RelatedPropertiesSpecification.ts
> +   *
unnecessary line

2021-09-22 05:27 UTC, grigasp commented on full-stack-tests/presentation/src/frontend/Hierarchies.test.ts
> +import {expect} from "chai";
formatting

2021-09-22 05:27 UTC, grigasp commented on presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json
> +            "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json
> +            "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json
> +            "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json
> +                "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json
> +            "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on presentation/backend/assets/supplemental-presentation-rules/BisCore.PresentationRuleSet.json
> +            "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on test-apps/presentation-test-app/assets/presentation_rules/IModelIndex.PresentationRuleSet.json
> +              "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on test-apps/presentation-test-app/assets/presentation_rules/IModelIndex.PresentationRuleSet.json
> +              "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on test-apps/presentation-test-app/assets/presentation_rules/VisibilityWidget.SpatialBreakdown-GroupedByClass.PresentationRuleSet.json
> +                "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on test-apps/presentation-test-app/assets/presentation_rules/VisibilityWidget.SpatialBreakdown-GroupedByClass.PresentationRuleSet.json
> +              "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on test-apps/presentation-test-app/assets/presentation_rules/VisibilityWidget.SpatialBreakdown-GroupedByClass.PresentationRuleSet.json
> +              "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on test-apps/presentation-test-app/assets/presentation_rules/VisibilityWidget.SpatialBreakdown.PresentationRuleSet.json
> +                "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on test-apps/presentation-test-app/assets/presentation_rules/VisibilityWidget.SpatialBreakdown.PresentationRuleSet.json
> +              "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on test-apps/presentation-test-app/assets/presentation_rules/VisibilityWidget.SpatialBreakdown.PresentationRuleSet.json
> +              "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on ui/framework/rulesets/Categories.json
> +              "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on ui/framework/rulesets/Models.json
> +                  "className": "ModelContainsElements"
ModelModelsElement?

2021-09-22 05:27 UTC, grigasp commented on ui/framework/src/ui-framework/imodel-components/spatial-tree/SpatialBreakdown.json
> +                "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on ui/framework/src/ui-framework/imodel-components/spatial-tree/SpatialBreakdown.json
> +              "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on ui/framework/src/ui-framework/imodel-components/spatial-tree/SpatialBreakdown.json
> +              "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on ui/framework/src/ui-framework/imodel-components/spatial-tree/SpatialBreakdown.GroupedByClass.json
> +                "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on ui/framework/src/ui-framework/imodel-components/spatial-tree/SpatialBreakdown.GroupedByClass.json
> +              "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 05:27 UTC, grigasp commented on ui/framework/src/ui-framework/imodel-components/spatial-tree/SpatialBreakdown.GroupedByClass.json
> +              "targetClass": {
unnecessary target class - it matches target of the relationship

2021-09-22 10:18 UTC, grigasp reviewed
Looks good. Missing pieces:
- [ ] `rush extract-api`
- [ ] `rush change`
- [ ] `NextVersion.md`

2021-09-22 20:18 UTC, grigasp approved these changes

2021-09-22 20:23 UTC, bsteinbk approved these changes

2021-09-22 20:42 UTC, merged