Remove ChangeSetApplyOption argument from db.applyChangeset
imodeljs/imodeljs pull request #2313
Opened 2021-09-21 13:38 UTC by kabentley

can be inferred from changesetId

depends on [#194761](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02/pullrequest/194761)

2021-09-21 13:40 UTC, kabentley commented
> Note: this will cause merge conflicts, since I made the enum @internal in another PR so that this wouldn't be a breaking change

2021-09-22 19:27 UTC, ramanujam-raman approved these changes

2021-09-22 20:33 UTC, pmconne commented on common/api/bentleyjs-core.api.md
> +export enum ExtensionStatus {
re-run extract-api?

2021-09-22 20:33 UTC, pmconne requested changes
You appear to have merged master into your branch. Master was just merged into imodel02. I merged imodel02 into your branch. Please rebuild and rerun lint, extract-api, cover, etc.

2021-09-22 20:38 UTC, jchick-bentley approved these changes

2021-09-22 22:52 UTC, merged