Update to Electron 14
imodeljs/imodeljs pull request #2364
Opened 2021-09-28 21:45 UTC by wgoehrig

This should fix certa tests running in electron not reporting results correctly during `rush build`/`rush cover`.

Unfortunately there are still some issues debugging certa electron tests.  I'll have to tackle that in another PR.

2021-09-28 21:52 UTC, calebmshafer reviewed
Can you update NextVersion.md?

The changes look good, I'll test them out locally now.

2021-09-28 22:13 UTC, pmconne requested changes
I will take this for a spin in display-test-app and display-performance-test-app tomorrow morning.

2021-09-29 01:17 UTC, calebmshafer approved these changes
Debugging in core and rpc full stack test and ui-test-app are working on both Mac and Windows for me. I'll let Paul play around with the other test apps but LGTM.

2021-09-29 05:16 UTC, grigasp approved these changes

2021-09-29 13:06 UTC, pmconne approved these changes

2021-09-29 15:04 UTC, bsteinbk approved these changes

2021-09-29 15:46 UTC, merged