Fixed logic for getting files and folder by path
imodeljs/imodeljs pull request #254
Opened 2020-11-18 09:56 UTC by PauliusGrigaliunas

2020-11-18 09:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=254) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=254) before we can accept your contribution.<br/><hr/>**Paulius Grigaliunas** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/imodeljs/imodeljs?pullRequest=254) it.</sub>

2020-11-18 10:05 UTC, tomaspakala commented on clients/projectshare/src/ProjectShareClient.ts
> +   * @param folderId Id of the folder where we need to upload that file.
Should be:
* @param folderId of the folder you want to delete.

2020-11-18 10:06 UTC, tomaspakala commented on clients/projectshare/src/ProjectShareClient.ts
> +
Single new line

2020-11-18 10:27 UTC, tomaspakala reviewed
Mainly some naming and code documentation should be updated a bit

2020-11-18 10:27 UTC, tomaspakala commented on clients/projectshare/src/ProjectShareClient.ts
> +
Single new line

2020-11-18 10:27 UTC, tomaspakala commented on clients/projectshare/src/ProjectShareClient.ts
> +   * @param folderId Id of the folder where we need to upload that file.
Should be:
*@param folderId of the folder you want to delete.

2020-11-23 15:27 UTC, calebmshafer commented
@PauliusGrigaliunas can you sign the CLA?  I'll kick off a new build as well.

2020-11-23 15:27 UTC, calebmshafer commented
/azp run

2020-11-24 16:39 UTC, calebmshafer commented
/azp run

2020-11-24 18:02 UTC, calebmshafer commented
@PauliusGrigaliunas it looks like the build is failing with the changelog files. Can you run `rush change`?

2020-11-24 20:05 UTC, calebmshafer requested changes
it looks like the build is failing with the changelog files. Can you run `rush change` to add one?

2020-11-25 14:29 UTC, calebmshafer commented
/azp run

2020-11-25 15:17 UTC, calebmshafer commented
/azp run

2020-11-30 19:40 UTC, calebmshafer requested changes
@PauliusGrigaliunas it looks like there are a few lint failures that still need to be cleaned up. Mind taking a look at them?  https://dev.azure.com/imodeljs/imodeljs/_build/results?buildId=2390&view=logs&j=49d0b678-52ae-56ca-d936-f4e8771f3f89

2020-12-01 08:00 UTC, pgrigaliunas commented
> @PauliusGrigaliunas it looks like there are a few lint failures that still need to be cleaned up. Mind taking a look at them? https://dev.azure.com/imodeljs/imodeljs/_build/results?buildId=2390&view=logs&j=49d0b678-52ae-56ca-d936-f4e8771f3f89

solved

2020-12-01 13:51 UTC, calebmshafer commented
/azp run

2020-12-06 20:47 UTC, calebmshafer commented
@PauliusGrigaliunas going to kick off a set of builds for this now. However I noticed that #340 had a number of similar changes?  Are both of these PRs still necessary and if so is there a specific order to them?

2020-12-06 23:31 UTC, tomaspakala commented
@calebmshafer #340 is based on this branch. There is no order but Paulius was working on improving integration tests in another branch while waiting for this branch to be merger.

2020-12-07 19:15 UTC, calebmshafer approved these changes

2020-12-07 20:11 UTC, calebmshafer requested changes
@PauliusGrigaliunas can you run `rush extract-api` after rebuilding?  The CI is currently failing due to that.

2020-12-09 13:29 UTC, calebmshafer commented
Closing in favor of #340.

2020-12-09 13:29 UTC, closed without merging