Presentation: Add ability to specify custom property value renderer
imodeljs/imodeljs pull request #311
Opened 2020-11-25 15:18 UTC by roluk

To use a custom property value renderer:
1. Override `renderer` property using presentation rules:
    ```json
    {
      "ruleType": "ContentModifier",
      "class": {
        "schemaName": "BisCore",
        "className": "Element"
      },
      "propertyOverrides": [
        {
          "name": "Model",
          "renderer": {
            "rendererName": "my_custom_renderer"
          }
        }
      ]
    }
    ```
2. Define mapping between `rendererName` and a custom renderer:
    ```typescript
    PropertyValueRendererManager.defaultManager.registerRenderer("my_custom_renderer", new MyCustomRenderer());
    ```

2020-11-25 15:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=311) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/imodeljs/imodeljs?pullRequest=311) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/imodeljs/imodeljs?pullRequest=311) it.</sub>

2020-11-25 15:28 UTC, pmconne approved these changes
This is a rubber stamp approval - I don't understand why the Display team is flagged as a code owner.

2020-11-25 16:17 UTC, calebmshafer commented
> This is a rubber stamp approval - I don't understand why the Display team is flagged as a code owner.

@pmconne looks like the change to only have `@imodeljs/core` as a CODEOWNER of the changelogs and api/summary changes hasn't made its way to the imodel02 branch.

2020-11-26 12:04 UTC, grigasp requested changes

2020-11-26 12:04 UTC, grigasp commented on docs/learning/Terminology.md
No idea how this file got here, but it looks like a duplicate of `docs/learning/presentation/Content/Terminology.md` and should be removed.

2020-11-26 17:04 UTC, grigasp approved these changes

2020-11-27 08:58 UTC, merged