Add ability for caller to override quantity display format per QuantityType.
imodeljs/imodeljs pull request #351
Opened 2020-12-03 15:12 UTC by bsteinbk

This PR contains a sub-set of PR #326 since these changes are needed as soon as possible. This PR does not contain the CustomFormatter implementation added by the Civil group. The Civil group have some changes they want to make to that code before merging with master.

2020-12-03 15:16 UTC, pmconne requested changes
Why `any`?

2020-12-03 21:36 UTC, DanEastBentley approved these changes

2020-12-03 21:55 UTC, pmconne approved these changes

2020-12-07 22:46 UTC, calebmshafer requested changes

2020-12-08 00:40 UTC, bsteinbk commented on common/api/imodeljs-frontend.api.md
> +// @beta
Reverted tag back to alpha. Also add SurveyFeet test to mimic native unit conversion test.

2020-12-08 13:54 UTC, calebmshafer approved these changes

2020-12-08 13:54 UTC, calebmshafer commented on core/quantity/src/Formatter/Format.ts
> +  public toJson(): FormatProps {
At some point we probably should rename name this to `toJSON` for consistency with how we use it in other places.  However, not needed in this PR.

2020-12-08 15:42 UTC, merged

2020-12-08 16:26 UTC, calebmshafer commented
@mergifyio backport release/2.10.0