Section cut views
imodeljs/imodeljs pull request #394
Opened 2020-12-09 21:07 UTC by pmconne

Description forthcoming...

[Corresponding native PR](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodel02/pullrequest/130286).

2020-12-09 21:17 UTC, pmconne commented
Closing - wrong target branch.

2020-12-09 21:49 UTC, bbastings reviewed
ViewClipModifyTool changes are approved.

2020-12-10 13:27 UTC, markschlosseratbentley requested changes

2020-12-10 13:30 UTC, pmconne commented on docs/changehistory/NextVersion.md
> +A [DisplayStyleState]($frontend) can now be configured to produce section-cut graphics from the view's [ClipVector]($geometry-core). In the image below, a clipping plane has been applied to produce a
/s/solid/hollow

2020-12-10 13:33 UTC, markschlosseratbentley commented on docs/changehistory/NextVersion.md
> +A [DisplayStyleState]($frontend) can now be configured to produce section-cut graphics from the view's [ClipVector]($geometry-core). In the image below, a clipping plane has been applied to produce a
Good stuff.  Another minor typo -- 'hoolow'

2020-12-10 13:35 UTC, pmconne commented on docs/changehistory/NextVersion.md
> +A [DisplayStyleState]($frontend) can now be configured to produce section-cut graphics from the view's [ClipVector]($geometry-core). In the image below, a clipping plane has been applied to produce a
What a dummy. Fixed.

2020-12-10 15:43 UTC, markschlosseratbentley commented
Is it expected that clip style lines should look like this?

![image](https://user-images.githubusercontent.com/47000437/101794123-87c14480-3ad4-11eb-908a-cb73f2ccfd4b.png)

![image](https://user-images.githubusercontent.com/47000437/101793595-f8b42c80-3ad3-11eb-94fd-dc003e533b25.png)

2020-12-10 15:49 UTC, pmconne commented
> Is it expected that clip style lines should look like this?

@markschlosseratbentley Yes, that keyin is for testing overriding aspects of section-cut graphics symbology.
[Here's the code that produces it](https://github.com/imodeljs/imodeljs/blob/6f6bef8b1040ce375d6809f70b36dd4d8d39f485/core/frontend-devtools/src/tools/ClipTools.ts#L138).

2020-12-10 15:49 UTC, pmconne commented
@markschlosseratbentley if your question is about the diagonal edges, that's mentioned in the TODO in PR description.

2020-12-10 15:51 UTC, markschlosseratbentley commented
> @markschlosseratbentley if your question is about the diagonal edges, that's mentioned in the TODO in PR description.

Yes, that's what I was referring to - Ah, okay, I see it in the TODO.

2020-12-10 15:52 UTC, markschlosseratbentley commented
> > Is it expected that clip style lines should look like this?
> 
> @markschlosseratbentley Yes, that keyin is for testing overriding aspects of section-cut graphics symbology.
> [Here's the code that produces it](https://github.com/imodeljs/imodeljs/blob/6f6bef8b1040ce375d6809f70b36dd4d8d39f485/core/frontend-devtools/src/tools/ClipTools.ts#L138).

Thanks.

2020-12-10 15:57 UTC, markschlosseratbentley commented
I built this and tested it out - it works well for me.

2020-12-10 15:58 UTC, markschlosseratbentley approved these changes

2020-12-10 16:00 UTC, pmconne commented
> ViewClipModifyTool changes are approved.

@bbastings but you didn't click "Approve".

2020-12-10 16:04 UTC, bbastings approved these changes

2020-12-10 16:05 UTC, merged