New EC-102 rule for abstract base class
imodeljs/imodeljs pull request #439
Opened 2020-12-15 20:11 UTC by christophermlawson

New EC rule (102) that an abstract class must only derive from an abstract base class.

2020-12-15 20:40 UTC, scsewall approved these changes
Approving the rule concept, did not review the implementation.

2020-12-21 18:07 UTC, calebmshafer requested changes
@christophermlawson can you run extract-api?  The build is currently failing due to an outdated file.

2021-01-12 12:48 UTC, ColinKerr approved these changes

2021-01-21 16:08 UTC, calebmshafer approved these changes

2021-01-27 12:31 UTC, merged