Presentation: add documentation for breaking change
imodeljs/imodeljs pull request #541
Opened 2021-01-08 14:31 UTC by saskliutas

Added documentation for breaking change to the `ContentRelatedInstances` specification.
Added more examples to `RelationshipPath` specification documentation.

2021-01-08 14:33 UTC, pmconne approved these changes

2021-01-08 14:56 UTC, grigasp requested changes

2021-01-08 14:56 UTC, grigasp commented on docs/learning/presentation/RelationshipPathSpecification.md
> +`count` | No | `number \| "*"` | 1 | Number of times the relationship should be traversed. If "*" used the result of previous step will be included also.
```suggestion
`count` | No | `number \| "*"` | 1 | Number of times the relationship should be traversed. `"*"` makes the step optional, so results of previous step are also included in results of this step, no matter if this step has any output of its own or not.

```

2021-01-08 14:56 UTC, grigasp commented on docs/changehistory/NextVersion.md
> +Behavior of `ContentRelatedInstances` specification used in content rules was changed. It used to include input instance in a result if `relationshipPaths` property had paths consisting of all steps
```suggestion
Behavior of `ContentRelatedInstances` specification used in content rules was changed. It used to include input instances into the result if all paths in `relationshipPaths` property had `count: "*"` and target class matched input instance class. The behavior was changed to match cases where steps `relationshipPaths` have `count` set to specific number - the result only includes instances resulting from step outputs. See [RelationshipPathSpecification documentation](../learning/presentation/RelationshipPathSpecification.md) for more details and examples.

Example:
```

2021-01-11 06:28 UTC, grigasp approved these changes

2021-01-11 09:45 UTC, merged