Add wildcard option for modelName in dpta #563418
imodeljs/imodeljs pull request #927
Opened 2021-03-08 19:45 UTC by hnn0003

2021-03-08 20:01 UTC, MarcNeely approved these changes

2021-03-08 20:12 UTC, pmconne requested changes
An iModel can contain any number of models. Please use "iModel" to refer to the file and "model" to refer to individual models within it.

2021-03-08 20:12 UTC, pmconne commented on test-apps/display-performance-test-app/README.md
> +If you wish to specify multiple models in the same folder, you can use a asterisk wildcard instead of a specific model name to test multiple models matching the given wildcard. This is NOT case-sensi
By "model" you mean "iModel", correct?

2021-03-08 20:12 UTC, pmconne commented on test-apps/display-performance-test-app/src/frontend/DisplayPerformanceTestApp.ts
> +  const matchingModels: string[] = [];
These are files (iModels), not models.

2021-03-12 14:53 UTC, pmconne approved these changes
I still see a bunch of "model" in the code where you mean "iModel" but ok.

2021-03-12 15:06 UTC, merged